language: scala
scala:
   - 2.11.7
   - 2.11.8
   - 2.12.1

jdk:
  - oraclejdk8

script:
  - sbt clean test

# required until bug is fixed: https://github.com/travis-ci/travis-ci/issues/3259
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
